config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/phone_books')
  resources :phone_books do
    member do
      get :import
      post :import
    end
  end
  resources :phone_book_entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone_book.rb
class PhoneBook < ApplicationRecord
  has_many :phone_book_entries

  validates :title, presence: true, uniqueness: true, format: { with: /\A[a-z\s]+\z/i }
end

app/models/phone_book_entry.rb
class PhoneBookEntry < ApplicationRecord
  belongs_to :phone_book

  before_save :cleanup_phone_numbers

  validates :name, presence: true, uniqueness: { scope: :phone_book_id }
  validates :phone_office, :phone_mobile, :phone_other, format: { with: /\A\+?[\d\s]+\z/, message: :invalid_phone_number_format }, allow_blank: true
  validate :has_at_least_one_phone_number

  scope :search, -> (query_string) {
    query = "%#{query_string.downcase}%"
    where(
        'lower(name) LIKE ? OR lower(phone_office) LIKE ? OR lower(phone_mobile) LIKE ? OR lower(phone_other) LIKE ?',
        query, query, query, query
    )
  }

  private

  def has_at_least_one_phone_number
    unless [phone_office, phone_mobile, phone_other].map(&:present?).any?
      errors.add(:base, :has_at_least_one_phone_number_required)
    end
  end

  def cleanup_phone_numbers
    self.phone_office.delete!(' ') if self.phone_office.present?
    self.phone_mobile.delete!(' ') if self.phone_mobile.present?
    self.phone_other.delete!(' ') if self.phone_other.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    if cookies['locale'].nil? || params[:locale]
      I18n.locale = params[:locale] || I18n.default_locale
      cookies['locale'] = I18n.locale
    else
      I18n.locale = cookies['locale']
    end
  end
end

app/controllers/phone_book_entries_controller.rb
class PhoneBookEntriesController < ApplicationController
  before_action :set_phone_book_entry, only: [:show, :edit, :update, :destroy]

  # GET /phone_book_entries
  # GET /phone_book_entries.json
  def index
    if params[:q].present?
      @phone_book_entries = PhoneBookEntry.search(params[:q])
    else
      @phone_book_entries = PhoneBookEntry.all
    end
  end

  # GET /phone_book_entries/1
  # GET /phone_book_entries/1.json
  def show
  end

  # GET /phone_book_entries/new
  def new
    @phone_book_entry = PhoneBookEntry.new
  end

  # GET /phone_book_entries/1/edit
  def edit
  end

  # POST /phone_book_entries
  # POST /phone_book_entries.json
  def create
    @phone_book_entry = PhoneBookEntry.new(phone_book_entry_params)

    respond_to do |format|
      if @phone_book_entry.save
        notice = t('successful.messages.created', model: PhoneBookEntry.model_name.human)
        format.html { redirect_to @phone_book_entry, notice: notice }
        format.json { render :show, status: :created, location: @phone_book_entry }
      else
        format.html { render :new }
        format.json { render json: @phone_book_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_book_entries/1
  # PATCH/PUT /phone_book_entries/1.json
  def update
    respond_to do |format|
      if @phone_book_entry.update(phone_book_entry_params)
        notice = t('successful.messages.updated', model: PhoneBookEntry.model_name.human)
        format.html { redirect_to @phone_book_entry, notice: notice }
        format.json { render :show, status: :ok, location: @phone_book_entry }
      else
        format.html { render :edit }
        format.json { render json: @phone_book_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_book_entries/1
  # DELETE /phone_book_entries/1.json
  def destroy
    phone_book = @phone_book_entry.phone_book
    @phone_book_entry.destroy
    respond_to do |format|
      notice = t('successful.messages.deleted', model: PhoneBookEntry.model_name.human)
      format.html { redirect_to phone_book, notice: notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_book_entry
      @phone_book_entry = PhoneBookEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_book_entry_params
      params.require(:phone_book_entry).permit(:phone_book_id, :name, :phone_office, :phone_mobile, :phone_other)
    end
end

app/controllers/phone_books_controller.rb
class PhoneBooksController < ApplicationController
  before_action :set_phone_book, only: [:show, :edit, :update, :destroy, :import]

  # GET /phone_books
  # GET /phone_books.json
  def index
    @phone_books = PhoneBook.all
  end

  # GET /phone_books/1
  # GET /phone_books/1.json
  def show
    @entries = @phone_book.phone_book_entries.order(:name)
  end

  # GET /phone_books/new
  def new
    @phone_book = PhoneBook.new
  end

  # GET /phone_books/1/edit
  def edit
  end

  # POST /phone_books
  # POST /phone_books.json
  def create
    @phone_book = PhoneBook.new(phone_book_params)

    respond_to do |format|
      if @phone_book.save
        notice = t('successful.messages.created', model: PhoneBook.model_name.human)
        format.html { redirect_to @phone_book, notice: notice }
        format.json { render :show, status: :created, location: @phone_book }
      else
        format.html { render :new }
        format.json { render json: @phone_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_books/1
  # PATCH/PUT /phone_books/1.json
  def update
    respond_to do |format|
      if @phone_book.update(phone_book_params)
        notice = t('successful.messages.updated', model: PhoneBook.model_name.human)
        format.html { redirect_to @phone_book, notice: notice }
        format.json { render :show, status: :ok, location: @phone_book }
      else
        format.html { render :edit }
        format.json { render json: @phone_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_books/1
  # DELETE /phone_books/1.json
  def destroy
    @phone_book.destroy
    respond_to do |format|
      notice = t('successful.messages.deleted', model: PhoneBook.model_name.human)
      format.html { redirect_to phone_books_url, notice: notice }
      format.json { head :no_content }
    end
  end

  # GET /phone_books/1/import
  # POST /phone_books/1/import
  def import
    @entries_with_errors = []

    if request.post?
      require 'csv'
      imported_count = 0
      csv_text = File.read(params[:file].path)
      csv = CSV.parse(csv_text, :headers => true)
      csv.each do |row|
        entry = PhoneBookEntry.new(row.to_hash.merge(phone_book_id: @phone_book.id))
        if entry.save
          imported_count += 1
        else
          @entries_with_errors << entry
        end
      end
      flash[:notice] = t('.successfully_imported', count: imported_count) if imported_count > 0
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_book
      @phone_book = PhoneBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_book_params
      params.require(:phone_book).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def material_icon(name, text = nil)
    tag = content_tag(:i, name, class: 'material-icons')
    text.present? ? tag += ' ' + text : tag
  end
end

app/helpers/phone_book_entries_helper.rb
module PhoneBookEntriesHelper
end

app/helpers/phone_books_helper.rb
module PhoneBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yealink Phone Book</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to material_icon('contact_phone', t('app_name')), phone_books_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbar"
        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="/phone_books">Phone Books <span class="sr-only">(current)</span></a>
          </li> -->
        </ul>
        <%= form_tag(phone_book_entries_path, method: :get, class: 'form-inline') do %>
          <%= text_field_tag(:q, params[:q], class: 'form-control', placeholder: t('search')) %>
        <% end %>
        <ul class="navbar-nav ml-2">
          <div class="btn-group">
            <li class="nav-item dropdown">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <%= material_icon('translate') %>
              </button>
              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to 'English', { locale: :en }, class: 'dropdown-item' %>
                <%= link_to 'Deutsch', { locale: :de }, class: 'dropdown-item' %>
              </div>
            </li>
          </div>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <p class="text-right"><small><%= t('app_name') %> <%= Time.now.year %></small></p>
      </div>
    </footer>
  </body>
</html>

app/views/phone_book_entries/_form.html.erb
<%= form_with(model: phone_book_entry, local: true) do |form| %>
  <% if phone_book_entry.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <h4 class="alert-heading"><%= t('errors.template.header', :model => PhoneBookEntry.model_name.human, :count => phone_book_entry.errors.count) %></h4>
      <ul class="mb-0">
      <% phone_book_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% if params[:phone_book_id].present? %>
    <%= form.hidden_field :phone_book_id, value: params[:phone_book_id] %>
  <% else %>
    <div class="form-group">
      <%= form.label :phone_book_id %>
      <%= form.collection_select :phone_book_id, PhoneBook.all, :id, :title, {}, id: :phone_book_entry_phone_book_id, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :phone_book_entry_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_office %>
    <%= form.text_field :phone_office, id: :phone_book_entry_phone_office, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_mobile %>
    <%= form.text_field :phone_mobile, id: :phone_book_entry_phone_mobile, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_other %>
    <%= form.text_field :phone_other, id: :phone_book_entry_phone_other, class: 'form-control' %>
  </div>

  <%= form.submit nil, class: 'btn btn-primary mb-2' %>
<% end %>

app/views/phone_book_entries/_table.html.erb
<% if entries.blank? %>
 <p><em><%= t('no_results') %></em></p>

<% else %>
  <table class="table">
    <thead>
      <tr>
        <% if show_phone_book %>
            <th><%= PhoneBook.model_name.human %></th>
        <% end %>
        <th><%= PhoneBookEntry.human_attribute_name(:name) %></th>
        <th><%= PhoneBookEntry.human_attribute_name(:phone_office) %></th>
        <th><%= PhoneBookEntry.human_attribute_name(:phone_mobile) %></th>
        <th><%= PhoneBookEntry.human_attribute_name(:phone_other) %></th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% entries.each do |phone_book_entry| %>
        <tr>
          <% if show_phone_book %>
              <td><%= phone_book_entry.phone_book.title %></td>
          <% end %>
          <td><b><%= link_to highlight(phone_book_entry.name, params[:q]), phone_book_entry %></b></td>
          <td><%= highlight(phone_book_entry.phone_office, params[:q]) %></td>
          <td><%= highlight(phone_book_entry.phone_mobile, params[:q]) %></td>
          <td><%= highlight(phone_book_entry.phone_other, params[:q]) %></td>
          <td><%= link_to material_icon('edit'), edit_phone_book_entry_path(phone_book_entry) %></td>
          <td><%= link_to material_icon('delete'), phone_book_entry, method: :delete, data: { confirm: t('confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/phone_book_entries/edit.html.erb
<h1><%= t('edit_title', resource: PhoneBookEntry.model_name.human) %></h1>

<%= render 'form', phone_book_entry: @phone_book_entry %>

<%= link_to material_icon('arrow_back', t('back')), :back, class: 'btn btn-secondary' %>

app/views/phone_book_entries/index.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success mt-2" role="alert"><%= notice %></div>
<% end %>
<h1><%= PhoneBookEntry.model_name.human(count: 2) %></h1>

<%= render partial: 'table', locals: { entries: @phone_book_entries, show_phone_book: true } %>

app/views/phone_book_entries/new.html.erb
<h1><%= t('new_title', model: PhoneBookEntry.model_name.human) %></h1>

<%= render 'form', phone_book_entry: @phone_book_entry %>

<%= link_to material_icon('arrow_back', t('back')), :back, class: 'btn btn-secondary' %>

app/views/phone_book_entries/show.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success mt-2" role="alert"><%= notice %></div>
<% end %>

<table class="table">
  <tbody>
    <tr>
      <th><%= PhoneBook.model_name.human %></th>
      <td><%= @phone_book_entry.phone_book.title %></td>
    </tr>
    <tr>
      <th><%= PhoneBookEntry.human_attribute_name(:name) %></th>
      <td><%= @phone_book_entry.name %></td>
    </tr>
    <tr>
      <th><%= PhoneBookEntry.human_attribute_name(:phone_office) %></th>
      <td><%= @phone_book_entry.phone_office %></td>
    </tr>
    <tr>
      <th><%= PhoneBookEntry.human_attribute_name(:phone_mobile) %></th>
      <td><%= @phone_book_entry.phone_mobile %></td>
    </tr>
    <tr>
      <th><%= PhoneBookEntry.human_attribute_name(:phone_other) %></th>
      <td><%= @phone_book_entry.phone_other %></td>
    </tr>
  </tbody>
</table>

<%= link_to material_icon('edit', t('edit')), edit_phone_book_entry_path(@phone_book_entry), class: 'btn btn-secondary' %>
<%= link_to material_icon('delete', t('delete')), @phone_book_entry, method: :delete, data: { confirm: t('confirm') }, class: 'btn btn-danger' %>
<%= link_to material_icon('arrow_back', t('back')), phone_book_path(@phone_book_entry.phone_book), class: 'btn btn-secondary' %>

app/views/phone_books/_form.html.erb
<%= form_with(model: phone_book, local: true) do |form| %>
  <% if phone_book.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <h4 class="alert-heading"><%= t('errors.template.header', :model => PhoneBook.model_name.human, :count => phone_book.errors.count) %></h4>
      <ul class="mb-0">
      <% phone_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :phone_book_title, class: 'form-control' %>
  </div>

  <%= form.submit nil, class: 'btn btn-primary mb-2' %>
<% end %>

app/views/phone_books/edit.html.erb
<h1><%= t('edit_title', resource: PhoneBook.model_name.human) %></h1>

<%= render 'form', phone_book: @phone_book %>

<%= link_to material_icon('arrow_back', t('back')), phone_books_path, class: 'btn btn-secondary' %>

app/views/phone_books/import.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success mt-2" role="alert"><%= notice %></div>
<% end %>

<% if @entries_with_errors.any? %>
  <div class="alert alert-danger alert-dismissible mt-2" role="alert">
    <h4 class="alert-heading"><%= t('.import_errors', :count => @entries_with_errors.count) %></h4>
    <ul class="mb-0">
    <% @entries_with_errors.each do |entry| %>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= entry.name + ': ' if entry.name.present? %><%= message %></li>
      <% end %>
    <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<h1>Import</h1>

<p><%= t('.help_text_csv_format') %></p>
<p><code>name, phone_office, phone_mobile, phone_other</code></p>
<p><%= t('.help_text_duplicates') %></p>

<%= form_tag(import_phone_book_path, multipart: true) do %>
  <div class="form-group">
    <%= label_tag :file, t('.csv_file_label') %>
    <%= file_field_tag :file, class: 'form-control-file', required: true %>
  </div>
  <%= submit_tag nil, class: 'btn btn-primary mb-2' %>
<% end %>

<%= link_to material_icon('arrow_back', t('back')), @phone_book, class: 'btn btn-secondary' %>

app/views/phone_books/index.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success mt-2" role="alert"><%= notice %></div>
<% end %>

<h1><%= PhoneBook.model_name.human(count: 2) %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= PhoneBook.human_attribute_name(:title) %></th>
      <th>#</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_books.each do |phone_book| %>
      <tr>
        <td><b><%= link_to phone_book.title, phone_book %></b></td>
        <td><%= phone_book.phone_book_entries.count %></td>
        <td><%= link_to material_icon('edit'), edit_phone_book_path(phone_book) %></td>
        <td><%= link_to material_icon('delete'), phone_book, method: :delete, data: { confirm: t('confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to material_icon('add', t('new_title', model: PhoneBook.model_name.human)), new_phone_book_path, class: 'btn btn-primary' %>

app/views/phone_books/new.html.erb
<h1><%= t('new_title', model: PhoneBook.model_name.human) %></h1>

<%= render 'form', phone_book: @phone_book %>

<%= link_to material_icon('arrow_back', t('back')), phone_books_path, class: 'btn btn-secondary' %>

app/views/phone_books/show.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success mt-2" role="alert"><%= notice %></div>
<% end %>

<h1><%= @phone_book.title %></h1>
<p>URL: <code><%= phone_book_url(@phone_book, format: :xml) %></code></p>

<%= render partial: 'phone_book_entries/table', locals: { entries: @entries, show_phone_book: false } %>

<%= link_to material_icon('add', t('new_title', model: PhoneBookEntry.model_name.human)), new_phone_book_entry_path(phone_book_id: @phone_book.id), class: 'btn btn-primary' %>
<%= link_to material_icon('edit', t('edit')), edit_phone_book_path(@phone_book), class: 'btn btn-secondary' %>
<%= link_to material_icon('import_contacts', t('.import_entries')), import_phone_book_path(@phone_book), class: 'btn btn-secondary' %>
<%= link_to material_icon('arrow_back', t('back')), phone_books_path, class: 'btn btn-secondary' %>